{"name": "test_multiple_login_page_success[invalid_user4-wrong_password]", "status": "passed", "parameters": [{"name": "username", "value": "'invalid_user4'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1753502348146, "stop": 1753502350249, "uuid": "ab2c9f82-b4ef-417b-92d7-71f05a82bbff", "historyId": "8169f900955b8e47d48e3638b02b295f", "testCaseId": "90d4f72dd78db4ae114ce1f1cc9587a0", "fullName": "tests.test_multiple_login#test_multiple_login_page_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_multiple_login"}, {"name": "host", "value": "ahmads-MacBook-Pro.local"}, {"name": "thread", "value": "53821-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_multiple_login"}], "titlePath": ["tests", "test_multiple_login.py"]}