{"name": "test_multiple_login_page_success[invalid_user4-wrong_password]", "status": "passed", "parameters": [{"name": "username", "value": "'invalid_user4'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1753503459590, "stop": 1753503461327, "uuid": "9152497b-2bc1-4f50-8f47-01e432711d66", "historyId": "8169f900955b8e47d48e3638b02b295f", "testCaseId": "90d4f72dd78db4ae114ce1f1cc9587a0", "fullName": "tests.test_multiple_login#test_multiple_login_page_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_multiple_login"}, {"name": "host", "value": "ahmads-MacBook-Pro.local"}, {"name": "thread", "value": "58931-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_multiple_login"}], "titlePath": ["tests", "test_multiple_login.py"]}